apiVersion: v1
kind: Pod
metadata:
  name: bri-fiona-fan
  namespace: rock
  annotations: 
    student-name: "Brigitte Chavez"
    music-preference: "Rock alternativo, Trip-Hop, Soul, etc"
    favorite-band: "Moloko"
    personality: "Melómana empedernida :p"
spec:
  containers:
  - name: metalero
    image: nginx
  tolerations:
  - key: "music"
    operator: "Equal"
    value: "guitarra-electrica"
    effect: "NoSchedule"
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: style
            operator: In
            values:
            - metalero