apiVersion: v1
kind: Pod
metadata:
  name: james-calero-salsa
  namespace: salsa
  annotations:
    student-name: "James Calero 2243461"
    music-preference: "Salsa"
spec:
  containers:
  - name: diskman
    image: nginx
  tolerations:
  - key: "music"
    operator: "Equal"
    value: "sabor-latino"
    effect: "NoSchedule"
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: style
            operator: In
            values:
            - latino