apiVersion: v1
kind: Pod
metadata:
  name: kevin-steven-reggaeton
  namespace: reggaeton
  annotations:
    student-name: "Kevin Steven"
    music-preference: "Reggaeton"
spec:
  containers:
  - name: fiestero
    image: nginx
  tolerations:
  - key: "music"
    operator: "Equal"
    value: "perreo-intenso"
    effect: "NoSchedule"
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: style
            operator: In
            values:
            - rockero